PShape s;
int cols, rows;
int w = 1000, h = 2000;
int space = 15;
float[][] z;
float sound;
int blah = -1;
float move = 0;
int border = 2;
color strokeCol = color(30, 255, 255);
float rotX = 1, rotY = 0, rotZ = 0;
float speed = 0.01;
float density = 0.1;
float amp = 100;
float starRot = 0;
int bands = 16;
float[] spectrum = new float[bands];
float sum = 0;
float smooth = .2;

int band = 0;
